inherit_from:
  - .rubocop_todo.yml
  - .rubocop_rspec_base.yml

# All these metrics should go down over time.

Metrics/ClassLength:
  Max: 279

Metrics/CyclomaticComplexity:
  Max: 18

Metrics/LineLength:
  Max: 193

Metrics/MethodLength:
  Max: 49

Metrics/AbcSize:
  Max: 47

Metrics/BlockLength:
  Max: 45
  Exclude:
    - spec/**/*

Metrics/ModuleLength:
  Max: 210

Metrics/PerceivedComplexity:
  Max: 19
